server:
  port: 7777
  servlet:
    context-path: /pay-api
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  main:
    banner-mode: off
  application:
    name: im-live-pay
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: @namespace@
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: @namespace@
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://@nacos.server@?namespace=dev
  protocol:
    name: tri
    port: 17777



