kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nacos-node1-v1
  namespace: im-live
  labels:
    app: nacos-node1
    version: v1
  annotations:
    kubesphere.io/creator: dev-zhang
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nacos-node1
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nacos-node1
        version: v1
      annotations:
        kubesphere.io/creator: dev-zhang
        kubesphere.io/imagepullsecrets: '{}'
        kubesphere.io/restartedAt: '2023-11-28T02:19:53.371Z'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: container-vesjsy
          image: 'nacos/nacos-server:v2.2.0'
          ports:
            - name: tcp-8848
              containerPort: 8848
              protocol: TCP
            - name: http-9848
              containerPort: 9848
              protocol: TCP
            - name: http-9849
              containerPort: 9849
              protocol: TCP
          env:
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-conf
                  key: MYSQL_SERVICE_DB_NAME
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-conf
                  key: MYSQL_SERVICE_HOST
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-conf
                  key: MYSQL_SERVICE_PASSWORD
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-conf
                  key: MYSQL_SERVICE_USER
            - name: SPRING_DATASOURCE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: nacos-conf
                  key: SPRING_DATASOURCE_PLATFORM
            - name: MODE
              valueFrom:
                configMapKeyRef:
                  name: nacos-conf
                  key: MODE
            - name: NACOS_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nacos-conf
                  key: NACOS_SERVERS
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: nacos-node1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
