kind: ConfigMap
apiVersion: v1
metadata:
  name: nacos-conf
  namespace: im-live
  annotations:
    kubesphere.io/creator: dev-zhang
data:
  MODE: standalone
  MYSQL_SERVICE_DB_NAME: nacos
  MYSQL_SERVICE_HOST: mysql.im-live
  MYSQL_SERVICE_PASSWORD: root
  MYSQL_SERVICE_USER: root
  NACOS_SERVERS: 'nacos.im-live:8848'
  SPRING_DATASOURCE_PLATFORM: mysql
