server:
  port: 18880
  servlet:
    context-path: /user-api
spring:
  main:
    banner-mode: off
  application:
    name: im-live-user
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: @namespace@
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: @namespace@
  config:
    import:
      - optional:nacos:${spring.application.name}.yml

