server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  main:
    banner-mode: off
  application:
    name: im-gateway
  profiles:
    # 环境配置
    active: @profiles.active@


  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: @namespace@
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: @namespace@

    gateway:
      routes:
        # 资源服务代理配置
        - id: auth
          uri: lb://im-live-auth
          predicates:
            - Path=/auth-api/**
          filters:
          - PreserveHostHeader
        # 资源服务代理配置
        - id: msg
          uri: lb://im-live-msg
          predicates:
            - Path=/msg-api/**
  config:
    import:
      - optional:nacos:${spring.application.name}.yml

