spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://mysql.im-live:3306/common?useUnicode=true&characterEncoding=utf8
    username: root
    password: root